### ISSUE TITLE
Change Parameter name to match actual code

### ISSUE THREAD

**Issue by atreya-s** [mohsenhariri/medviz#5]
https://github.com/mohsenhariri/medviz/blob/f0685b7e5a8ba8d3f4516af93b25248ccf7cfdae/api/preprocessing/resampling_segmentation_bulk.py#L18-L23

```
def resample(
    path: PathType,
    voxel_size: List[float] = [1.0, 1.0, 1.0],
    method: str = "trilinear",
    out_path: Optional[PathType] = None,
    file_name: Optional[str] = None,
)
```

- The parameters defined in the resample method are different from what is defined in the esampling_segmentation_bulk file
- input_path < path
- output < out_path
- new_voxel_size < voxel_size

**Comment by mohsenhariri** [comment]
Thank you @atreya-s, It has been addressed in the pull requests #6 and #7.
